### PR TITLE
Fromdistro

### PR DESCRIPTION
**Pull request by michelmno**
Hello Frank,
please find a set of three patches while trying for embed in fedora and opensuse distro.

### CODE REVIEW

**Comment by fhaverkamp** [comment]
Hi Michel,

thanks for the contribution. Did you check that:
+CONFIG_ZLIB_PATH ?= $(shell /sbin/ldconfig -p | grep libz.so.1 | cut -d' ' -f4 | head -n1)

works for the other Linux distributions too? E.g. Ubuntu or RHEL?
Regards

Frank

**Comment by michelmno** [comment]
no I did not checked yet for Ubuntu or redhat/fedora. so hold on while I will try (do not know yet when)

**Comment by fhaverkamp** [comment]
Hi Michel,

I had a quick look at our lab systems and found:

haver@tul2eth3:~$ lsb_release  -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04 LTS
Release:    16.04
Codename:   xenial
haver@tul2eth3:~$ which ldconfig
**/sbin/ldconfig**
haver@tul2eth3:~$ 

[haver@tul4eth3 ~]$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.2 (Maipo)
[haver@tul4eth3 ~]$ which ldconfig
**/usr/sbin/ldconfig**

Well, got that we checked. So I guess your patch does not work for RHEL. Please invent something different that can cope with the different locations of ldconfig per Linux Distribution.

Regards

Frank

**Comment by fhaverkamp** [comment]
Can you enhance the path in the SLES case? Keeping a common spec file is of course a good idea.

**Comment by fhaverkamp** [comment]
[haver@tul4eth3 ~]$  ls -li /usr/sbin/ldconfig /sbin/ldconfig 
203856451 -rwxr-xr-x. 1 root root 941848 29. Okt 2015  /sbin/ldconfig
203856451 -rwxr-xr-x. 1 root root 941848 29. Okt 2015  /usr/sbin/ldconfig

**Pull request merged**
